# Generated by Django 4.0.2 on 2022-04-15 01:38

from django.db import migrations

def init_data(apps, schema_editor):
    Category = apps.get_model('courses', 'Category')
    Category.objects.create(name="Cong nghe phan mem")
    Category.objects.create(name="Khoa hoc du lieu")
    Category.objects.create(name="An toan thong tin")

    Tag = apps.get_model('courses', 'Tag')
    Tag.objects.create(name="lap trinh")
    Tag.objects.create(name="cong nghe")

    Course = apps.get_model('courses', 'Course')
    Course.objects.create(subject="Nhap mon CNPM", category_id=1)
    Course.objects.create(subject="Kiem thu phan mem", category_id=1)
    Course.objects.create(subject="Xay dung phan mem", category_id=1)
    Course.objects.create(subject="Nhap mon tri tue nhan tao", category_id=2)

    Lesson = apps.get_model('courses', 'Lesson')
    Lesson.objects.create(subject="Phan tich PM", content="Phan tich yeu cau phan mem", course_id=1)
    Lesson.objects.create(subject="Thiet ke PM", content="Mo hinh hoa va thiet ke phan mem", course_id=1)
    Lesson.objects.create(subject="Hien thuc PM", content="Lap trinh hien thuc phan mem theo thiet ke", course_id=1)
    Lesson.objects.create(subject="Tong quan kiem thu phan mem", content="Tong quan kiem thu phan mem", course_id=2)
    Lesson.objects.create(subject="Kiem thu hop den", content="Kiem thu hop den", course_id=2)
    Lesson.objects.create(subject="Kiem thu hop trang", content="Kiem thu hop trang", course_id=2)



class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rating_like'),
    ]

    operations = [
        migrations.RunPython(init_data)
    ]
