# Generated by Django 4.0.2 on 2022-04-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20220415_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pre_courses',
            field=models.ManyToManyField(null=True, to='courses.Course'),
        ),
    ]
