# Generated by Django 4.0.2 on 2022-04-23 11:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_userlessonview_lesson_viewers_userlessonview_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVOnline',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('intro', ckeditor.fields.RichTextField()),
                ('from_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('to_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
